### PR TITLE
Defaulting to Lagom 1.4.0-RC1

### PR DESCRIPTION
**Pull request by renatocaval**
* defaults to Scala 2.12.4
* updates macwire to 2.3.0
* updates ScalaTest to 3.0.4
* recommend properties overrides

### CODE REVIEW

**Comment by TimMoore** [comment]
When I compile this, I get a deprecation warning.

I needed to `set scalacOptions in ThisBuild += "-deprecation"` to see the details:

```
[warn] /Users/tmoore/Projects/tmp/hello/hello-api/src/main/scala/com/example/hello/api/HelloService.scala:47: Eta-expansion of zero-argument method values is deprecated. Did you intend to write HelloService.this.greetingsTopic()?
[warn]         topic(HelloService.TOPIC_NAME, greetingsTopic _)
[warn]                                        ^
[warn] one warning found
```

**Comment by TimMoore** [comment]
I also get the same deprecation warning about `play.crypto.secret` that I noted in the [Java template](https://github.com/lagom/lagom-java.g8/pull/26#issuecomment-355204756).

**Comment by TimMoore** [comment]
Do you think we should wait for the final release before merging, or get people started using it now?

**Comment by renatocaval** [comment]
I think we should cut it now. If someone starts a project today, we want them to start on the 1.4.x series.

**Comment by TimMoore** [comment]
OK... want to remove the [WIP] tags from the two pull requests and merge them then?

**Comment by renatocaval** [comment]
I did and like a "pro" I merged them without paying attention that `[WIP]` was being added to the merged git message :palmface:.

Worst, I've done it before on this same repo (2x :palmface:).

**Pull request merged**
