### PR TITLE
Add NotUsed serializer

### PR DESCRIPTION
**Pull request by octonato**

### CODE REVIEW

**Comment by ignasi35** [comment]
I think we should add this on lagom itself (https://github.com/lagom/lagom/issues/1270)

**Comment by ignasi35** [comment]
ah, just seen https://github.com/lagom/lagom/pull/1922.

Why this PR, then?

**Comment by octonato** [comment]
I have already added in Lagom https://github.com/lagom/lagom/pull/1922

But between today and the release of 1.5.2 or 1.6.0, we have a few/many days. Users starting a new project today can already get the `NotUsed` serializer configured.

**Review by marcospereira — COMMENTED** [review]
So, it looks like `stream-impl` here is not on par with what we have in https://github.com/lagom/lagom-java.g8/pull/53, correct? Is this related to the seeds or Lagom itself?

**Comment by octonato** [comment]
Correct. They are not exactly the same.

**Comment by octonato** [comment]
What about this one? @ignasi35 / @marcospereira 

Anything else to do here?

**Review by ignasi35 — APPROVED** [review]

**Pull request merged**
